apiVersion: v1
kind: Service
metadata:
  name: librechat-mongodb
  labels:
    app.kubernetes.io/name: librechat-mongodb
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: librechat-mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
